### ISSUE TITLE
HTTP header based authentication against Discourse

### ISSUE THREAD

**Issue by amotl** [huw/github-to-discourse#2]
According to [1], authenticating against Discourse will soon stop working using the `api_key` and `api_username` request parameters. Instead, the `Api-Key` and `Api-Username` HTTP headers should be used.

Our Discourse instances at [2] and [3] are already signaling that on the admin dashboard:

> We detected an API request using a deprecated authentication method. Please update it to use header based auth.

[1] https://meta.discourse.org/t/discourse-api-documentation/22706
[2] https://community.hiveeyes.org/
[3] https://community.panodata.org/

**Comment by huw** [comment]
I've drafted some changes at a0aebbc — are you able to clone the repo yourself and test it? I haven't used Discourse since the last update to this package so don't have a test environment on me.

**Comment by amotl** [comment]
Dear @huw,

thanks for your quick response. It looks like it works like a charm! Can I humbly ask if you can release this as an updated version on npmjs.org?

With kind regards,
Andreas.

**Comment by huw** [comment]
Done! Glad I could help, and thanks for providing all the details I needed to fix this ^_^

**Comment by amotl** [comment]
Thanks a bunch for fixing this so quickly!
